import { Sidebar } from '@/components/Sidebar'
import { QueryProvider } from '@/providers/queryProvider'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Toaster } from 'sonner'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<QueryProvider>
					<main className='flex h-full'>
						<Toaster position='top-center' richColors />
						<Sidebar />
						{children}
					</main>
				</QueryProvider>
			</body>
		</html>
	)
}
